using DocOrganizer.Application.Interfaces;
using DocOrganizer.Application.Interfaces.V3;
using DocOrganizer.Core.Models;
using Microsoft.Extensions.Logging;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats.Jpeg;
using SixLabors.ImageSharp.Processing;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using PdfSharp.Pdf;
using PdfSharp.Drawing;
using PdfSharpPdfDocument = PdfSharp.Pdf.PdfDocument;

namespace DocOrganizer.Infrastructure.Services.V3;

/// <summary>
/// PDF出力サービス - PDFsharp（オリジナル版）使用版
/// </summary>
public class PdfExportService : IPdfExportService
{
    private readonly IPdfService _pdfService;
    private readonly ILogger<PdfExportService> _logger;
    private readonly IHeicConversionService _heicConversionService;

    public event EventHandler<PdfExportProgressEventArgs>? ProgressChanged;

    public PdfExportService(
        IPdfService pdfService, 
        ILogger<PdfExportService> logger,
        IHeicConversionService heicConversionService)
    {
        _pdfService = pdfService;
        _logger = logger;
        _heicConversionService = heicConversionService;
    }

    public async Task<bool> ExportCurrentStateAsync(
        IEnumerable<PdfExportPageData> pageData, 
        PdfQualitySettings qualitySettings,
        string outputPath)
    {
        try
        {
            var pageList = pageData.ToList();
            _logger.LogInformation("[PdfExportService] PDF出力開始: {PageCount}ページ, 画質: {Quality}", 
                pageList.Count, qualitySettings.DisplayName);

            // 🔧 詳細デバッグログ: 入力データ検証
            await AppendDebugLogAsync($"[PdfExportService] 出力パス: {outputPath}");
            await AppendDebugLogAsync($"[PdfExportService] ページ数: {pageList.Count}");
            
            for (int i = 0; i < pageList.Count; i++)
            {
                var page = pageList[i];
                await AppendDebugLogAsync($"[PdfExportService] Page{i}: ImagePath='{page.ImagePath}', Rotation={page.Rotation}");
                
                // ファイル存在確認
                if (!File.Exists(page.ImagePath))
                {
                    await AppendDebugLogAsync($"[PdfExportService] ❌ ファイル不存在: {page.ImagePath}");
                    throw new FileNotFoundException($"画像ファイルが見つかりません: {page.ImagePath}");
                }
                else
                {
                    var fileInfo = new FileInfo(page.ImagePath);
                    await AppendDebugLogAsync($"[PdfExportService] ✅ ファイル確認: {page.ImagePath} (サイズ: {fileInfo.Length}バイト)");
                }
            }

            // 出力ディレクトリの作成
            var outputDir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
            {
                await AppendDebugLogAsync($"[PdfExportService] 出力ディレクトリ作成: {outputDir}");
                Directory.CreateDirectory(outputDir);
            }

            // PDFsharpを使用してPDF文書を作成
            await AppendDebugLogAsync("[PdfExportService] PDFsharp PdfDocument作成開始");
            
            using var document = new PdfSharpPdfDocument();
            
            // PDFメタデータ設定
            document.Info.Title = Path.GetFileNameWithoutExtension(outputPath);
            document.Info.Creator = "DocOrganizer V3.0";
            // document.Info.Producer は読み取り専用のため設定をスキップ
            document.Info.Subject = "Generated by DocOrganizer";
            document.Info.CreationDate = DateTime.Now;
            
            await AppendDebugLogAsync("[PdfExportService] PDFsharp PdfDocument作成完了");

            for (int i = 0; i < pageList.Count; i++)
            {
                var page = pageList[i];
                await AppendDebugLogAsync($"[PdfExportService] ページ{i + 1}/{pageList.Count}の処理開始");
                
                OnProgressChanged(new PdfExportProgressEventArgs
                {
                    CurrentPage = i + 1,
                    TotalPages = pageList.Count,
                    CurrentOperation = $"ページ {i + 1}/{pageList.Count} を処理中..."
                });

                try
                {
                    await ProcessPageToPdfAsync(page, document, qualitySettings);
                    await AppendDebugLogAsync($"[PdfExportService] ページ{i + 1}処理完了");
                }
                catch (Exception pageEx)
                {
                    await AppendDebugLogAsync($"[PdfExportService] ❌ ページ{i + 1}処理エラー: {pageEx.Message}");
                    throw new Exception($"ページ{i + 1}の処理でエラーが発生しました: {pageEx.Message}", pageEx);
                }
            }

            // PDF保存
            OnProgressChanged(new PdfExportProgressEventArgs
            {
                CurrentPage = pageList.Count,
                TotalPages = pageList.Count,
                CurrentOperation = "PDFファイルを保存中..."
            });

            await AppendDebugLogAsync($"[PdfExportService] PDF保存開始: {outputPath}");
            document.Save(outputPath);
            await AppendDebugLogAsync($"[PdfExportService] PDF保存完了: {outputPath}");
            
            // 保存結果確認
            if (File.Exists(outputPath))
            {
                var outputFileInfo = new FileInfo(outputPath);
                await AppendDebugLogAsync($"[PdfExportService] ✅ PDF出力成功: {outputPath} (サイズ: {outputFileInfo.Length}バイト)");
            }
            else
            {
                await AppendDebugLogAsync($"[PdfExportService] ❌ PDF出力失敗: ファイルが作成されませんでした");
                return false;
            }
            
            _logger.LogInformation("[PdfExportService] PDF出力完了: {OutputPath}", outputPath);
            return true;
        }
        catch (Exception ex)
        {
            await AppendDebugLogAsync($"[PdfExportService] ❌ 致命的エラー: {ex.GetType().Name}: {ex.Message}");
            await AppendDebugLogAsync($"[PdfExportService] スタックトレース: {ex.StackTrace}");
            if (ex.InnerException != null)
            {
                await AppendDebugLogAsync($"[PdfExportService] 内部例外: {ex.InnerException.Message}");
            }
            
            _logger.LogError(ex, "[PdfExportService] PDF出力エラー: {Error}", ex.Message);
            return false;
        }
    }

    public async Task<byte[]> ProcessPageImageAsync(PdfExportPageData pageData, PdfQualitySettings qualitySettings)
    {
        try
        {
            _logger.LogDebug("[PdfExportService] 画像処理開始: {ImagePath}, 回転: {Rotation}度", 
                pageData.ImagePath, pageData.Rotation);

            var imagePath = pageData.ImagePath;
            
            // ✅ HEIC判定と事前変換
            if (IsHeicFile(imagePath))
            {
                _logger.LogDebug("[PdfExportService] HEIC形式を検出、JPEG変換を実行: {OriginalPath}", imagePath);
                await AppendDebugLogAsync($"[ProcessPageImageAsync] HEIC形式検出: {imagePath}");
                
                // HeicConversionServiceを使用してJPEG変換
                imagePath = await _heicConversionService.ConvertHeicToTempJpegAsync(imagePath);
                
                _logger.LogDebug("[PdfExportService] HEIC→JPEG変換完了: {ConvertedPath}", imagePath);
                await AppendDebugLogAsync($"[ProcessPageImageAsync] HEIC→JPEG変換完了: {imagePath}");
            }

            // ImageSharpで処理（変換済みJPEGまたは他形式）
            using var image = await SixLabors.ImageSharp.Image.LoadAsync<SixLabors.ImageSharp.PixelFormats.Rgba32>(imagePath);

            // 🎯 サムネイルと同じ処理: EXIF Orientation自動補正（最重要修正）
            image.Mutate(x => x.AutoOrient());
            await AppendDebugLogAsync($"[ProcessPageImageAsync] AutoOrient()適用完了 - サムネイルと同じ向き処理");

            // 回転適用
            if (pageData.Rotation > 0)
            {
                image.Mutate(x => x.Rotate(pageData.Rotation));
                _logger.LogDebug("[PdfExportService] 画像回転適用: {Rotation}度", pageData.Rotation);
                await AppendDebugLogAsync($"[ProcessPageImageAsync] 追加回転適用: {pageData.Rotation}度");
            }

            // 画質設定に基づくリサイズ
            var currentSize = image.Size;
            var targetSize = CalculateTargetSize(currentSize, qualitySettings);
            
            if (targetSize != currentSize)
            {
                image.Mutate(x => x.Resize(new ResizeOptions
                {
                    Size = targetSize,
                    Mode = ResizeMode.Max
                }));
                _logger.LogDebug("[PdfExportService] 画像リサイズ: {OriginalSize} → {TargetSize}", 
                    currentSize, targetSize);
                await AppendDebugLogAsync($"[ProcessPageImageAsync] リサイズ完了: {currentSize} → {targetSize}");
            }

            // JPEG形式でエンコード（EXIF情報除去 + 高品質設定）
            using var ms = new MemoryStream();
            await image.SaveAsJpegAsync(ms, new JpegEncoder 
            { 
                Quality = qualitySettings.CompressionLevel,
                // EXIF情報を除去してPDFsharpでの重複回転を防ぐ
                SkipMetadata = true
            });

            await AppendDebugLogAsync($"[ProcessPageImageAsync] JPEG保存完了: {ms.Length}バイト, 品質: {qualitySettings.CompressionLevel}");
            return ms.ToArray();
        }
        catch (Exception ex)
        {
            await AppendDebugLogAsync($"[ProcessPageImageAsync] ❌ 画像処理エラー: {ex.Message}");
            _logger.LogError(ex, "[PdfExportService] 画像処理エラー: {ImagePath}, {Error}", 
                pageData.ImagePath, ex.Message);
            throw;
        }
    }

    private async Task ProcessPageToPdfAsync(PdfExportPageData pageData, PdfSharpPdfDocument document, PdfQualitySettings qualitySettings)
    {
        try
        {
            await AppendDebugLogAsync($"[ProcessPageToPdfAsync] 開始: {pageData.ImagePath}");
            
            // 画像データを処理
            var imageBytes = await ProcessPageImageAsync(pageData, qualitySettings);
            await AppendDebugLogAsync($"[ProcessPageToPdfAsync] 画像処理完了: {imageBytes.Length}バイト");

            // PDFページを作成
            var page = document.AddPage();
            page.Size = PdfSharp.PageSize.A4;
            page.Orientation = PdfSharp.PageOrientation.Portrait;
            
            await AppendDebugLogAsync($"[ProcessPageToPdfAsync] PDFページ作成完了: {page.Width}pt x {page.Height}pt");

            // XGraphicsを作成
            using var gfx = XGraphics.FromPdfPage(page);
            await AppendDebugLogAsync("[ProcessPageToPdfAsync] XGraphics作成完了");

            // XImageを作成（一時ファイル経由）
            var tempFilePath = Path.GetTempFileName() + ".jpg";
            try
            {
                await File.WriteAllBytesAsync(tempFilePath, imageBytes);
                await AppendDebugLogAsync($"[ProcessPageToPdfAsync] 一時ファイル作成: {tempFilePath}");
                using var image = XImage.FromFile(tempFilePath);
            await AppendDebugLogAsync($"[ProcessPageToPdfAsync] XImage作成完了: {image.PixelWidth}x{image.PixelHeight}");

            // A4サイズに合わせて描画位置とサイズを計算
            var pageSize = new XSize(page.Width, page.Height);
            var imageSize = new SixLabors.ImageSharp.Size(image.PixelWidth, image.PixelHeight);
            var drawRect = CalculateDrawingRectangle(imageSize, pageSize);
            
            await AppendDebugLogAsync($"[ProcessPageToPdfAsync] 描画矩形: {drawRect.X}, {drawRect.Y}, {drawRect.Width}, {drawRect.Height}");

            // 画像を描画
            await AppendDebugLogAsync("[ProcessPageToPdfAsync] 画像描画開始");
            gfx.DrawImage(image, drawRect);
            await AppendDebugLogAsync("[ProcessPageToPdfAsync] 画像描画完了");

                await AppendDebugLogAsync($"[ProcessPageToPdfAsync] ページ処理完了: {pageData.ImagePath}");
                _logger.LogDebug("[PdfExportService] PDFページ追加完了: {ImagePath}", pageData.ImagePath);
            }
            finally
            {
                // 一時ファイルの削除
                if (File.Exists(tempFilePath))
                {
                    File.Delete(tempFilePath);
                    await AppendDebugLogAsync($"[ProcessPageToPdfAsync] 一時ファイル削除: {tempFilePath}");
                }
            }
        }
        catch (Exception ex)
        {
            await AppendDebugLogAsync($"[ProcessPageToPdfAsync] ❌ エラー: {ex.GetType().Name}: {ex.Message}");
            await AppendDebugLogAsync($"[ProcessPageToPdfAsync] スタックトレース: {ex.StackTrace}");
            
            _logger.LogError(ex, "[PdfExportService] PDFページ処理エラー: {ImagePath}, {Error}", 
                pageData.ImagePath, ex.Message);
            throw;
        }
    }

    private SixLabors.ImageSharp.Size CalculateTargetSize(SixLabors.ImageSharp.Size currentSize, PdfQualitySettings qualitySettings)
    {
        var maxWidth = qualitySettings.MaxWidth;
        var maxHeight = qualitySettings.MaxHeight;

        // 最高画質の場合（MaxWidth=0, MaxHeight=0）は元画像サイズそのまま
        if (maxWidth == 0 && maxHeight == 0)
        {
            return currentSize;
        }

        if (currentSize.Width <= maxWidth && currentSize.Height <= maxHeight)
        {
            return currentSize;
        }

        var widthRatio = (double)maxWidth / currentSize.Width;
        var heightRatio = (double)maxHeight / currentSize.Height;
        var ratio = Math.Min(widthRatio, heightRatio);

        return new SixLabors.ImageSharp.Size(
            (int)(currentSize.Width * ratio),
            (int)(currentSize.Height * ratio)
        );
    }

    private XRect CalculateDrawingRectangle(SixLabors.ImageSharp.Size imageSize, XSize pageSize)
    {
        // A4ページ内で画像を中央配置・最大化
        var pageAspect = pageSize.Width / pageSize.Height;
        var imageAspect = (double)imageSize.Width / imageSize.Height;

        double width, height;
        if (imageAspect > pageAspect)
        {
            // 画像が横長：幅をページ幅に合わせる
            width = pageSize.Width;
            height = width / imageAspect;
        }
        else
        {
            // 画像が縦長：高さをページ高さに合わせる
            height = pageSize.Height;
            width = height * imageAspect;
        }

        // 中央配置
        var x = (pageSize.Width - width) / 2;
        var y = (pageSize.Height - height) / 2;

        return new XRect(x, y, width, height);
    }

    private void OnProgressChanged(PdfExportProgressEventArgs e)
    {
        ProgressChanged?.Invoke(this, e);
    }

    /// <summary>
    /// 🚨 緊急デバッグ: ファイルに詳細ログを出力（第16条準拠）
    /// </summary>
    private async Task AppendDebugLogAsync(string message)
    {
        try
        {
            var logMessage = $"[{DateTime.Now:yyyy-MM-dd HH:mm:ss.fff}] {message}";
            var logPath = @"C:\Users\217216X721451\github\DocOrganizer\release\DEBUG_LOG.txt";
            await System.IO.File.AppendAllTextAsync(logPath, logMessage + Environment.NewLine);
            System.Diagnostics.Debug.WriteLine($"[PDF_EXPORT_DEBUG] {message}");
        }
        catch
        {
            // ログ出力エラーは無視
        }
    }

    /// <summary>
    /// HEIC形式のファイルかどうかを判定
    /// </summary>
    private static bool IsHeicFile(string filePath)
    {
        var extension = Path.GetExtension(filePath).ToLowerInvariant();
        return extension == ".heic" || extension == ".heif";
    }
}