using DocOrganizer.Application.Interfaces;
using DocOrganizer.Application.Interfaces.V3;
using DocOrganizer.Core.Models;
using Microsoft.Extensions.Logging;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats.Jpeg;
using SixLabors.ImageSharp.Processing;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using PdfSharp.Pdf;
using PdfSharp.Drawing;
using PdfSharpPdfDocument = PdfSharp.Pdf.PdfDocument;

namespace DocOrganizer.Infrastructure.Services.V3;

/// <summary>
/// PDF出力サービス - PDFsharp（オリジナル版）使用版
/// </summary>
public class PdfExportService : IPdfExportService
{
    private readonly IPdfService _pdfService;
    private readonly ILogger<PdfExportService> _logger;
    private readonly IHeicConversionService _heicConversionService;
    private readonly IAutoCropService _autoCropService;

    public event EventHandler<PdfExportProgressEventArgs>? ProgressChanged;

    public PdfExportService(
        IPdfService pdfService,
        ILogger<PdfExportService> logger,
        IHeicConversionService heicConversionService,
        IAutoCropService autoCropService = null) // オプショナル（既存コードとの互換性）
    {
        _pdfService = pdfService;
        _logger = logger;
        _heicConversionService = heicConversionService;
        _autoCropService = autoCropService;
    }

    public async Task<bool> ExportCurrentStateAsync(
        IEnumerable<PdfExportPageData> pageData, 
        PdfQualitySettings qualitySettings,
        string outputPath)
    {
        try
        {
            var pageList = pageData.ToList();
            _logger.LogInformation("[PdfExportService] PDF出力開始: {PageCount}ページ, 画質: {Quality}", 
                pageList.Count, qualitySettings.DisplayName);

            // 🔧 詳細デバッグログ: 入力データ検証
            await AppendDebugLogAsync($"[PdfExportService] 出力パス: {outputPath}");
            await AppendDebugLogAsync($"[PdfExportService] ページ数: {pageList.Count}");
            
            for (int i = 0; i < pageList.Count; i++)
            {
                var page = pageList[i];
                await AppendDebugLogAsync($"[PdfExportService] Page{i}: ImagePath='{page.ImagePath}', Rotation={page.Rotation}");
                
                // ファイル存在確認
                if (!File.Exists(page.ImagePath))
                {
                    await AppendDebugLogAsync($"[PdfExportService] ❌ ファイル不存在: {page.ImagePath}");
                    throw new FileNotFoundException($"画像ファイルが見つかりません: {page.ImagePath}");
                }
                else
                {
                    var fileInfo = new FileInfo(page.ImagePath);
                    await AppendDebugLogAsync($"[PdfExportService] ✅ ファイル確認: {page.ImagePath} (サイズ: {fileInfo.Length}バイト)");
                }
            }

            // 出力ディレクトリの作成
            var outputDir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
            {
                await AppendDebugLogAsync($"[PdfExportService] 出力ディレクトリ作成: {outputDir}");
                Directory.CreateDirectory(outputDir);
            }

            // PDFsharpを使用してPDF文書を作成
            await AppendDebugLogAsync("[PdfExportService] PDFsharp PdfDocument作成開始");
            
            using var document = new PdfSharpPdfDocument();
            
            // PDFメタデータ設定
            document.Info.Title = Path.GetFileNameWithoutExtension(outputPath);
            document.Info.Creator = "DocOrganizer V3.0";
            // document.Info.Producer は読み取り専用のため設定をスキップ
            document.Info.Subject = "Generated by DocOrganizer";
            document.Info.CreationDate = DateTime.Now;
            
            await AppendDebugLogAsync("[PdfExportService] PDFsharp PdfDocument作成完了");

            for (int i = 0; i < pageList.Count; i++)
            {
                var page = pageList[i];
                await AppendDebugLogAsync($"[PdfExportService] ページ{i + 1}/{pageList.Count}の処理開始");
                
                OnProgressChanged(new PdfExportProgressEventArgs
                {
                    CurrentPage = i + 1,
                    TotalPages = pageList.Count,
                    CurrentOperation = $"ページ {i + 1}/{pageList.Count} を処理中..."
                });

                try
                {
                    await ProcessPageToPdfAsync(page, document, qualitySettings);
                    await AppendDebugLogAsync($"[PdfExportService] ページ{i + 1}処理完了");
                }
                catch (Exception pageEx)
                {
                    await AppendDebugLogAsync($"[PdfExportService] ❌ ページ{i + 1}処理エラー: {pageEx.Message}");
                    throw new Exception($"ページ{i + 1}の処理でエラーが発生しました: {pageEx.Message}", pageEx);
                }
            }

            // PDF保存
            OnProgressChanged(new PdfExportProgressEventArgs
            {
                CurrentPage = pageList.Count,
                TotalPages = pageList.Count,
                CurrentOperation = "PDFファイルを保存中..."
            });

            await AppendDebugLogAsync($"[PdfExportService] PDF保存開始: {outputPath}");
            document.Save(outputPath);
            await AppendDebugLogAsync($"[PdfExportService] PDF保存完了: {outputPath}");
            
            // 保存結果確認
            if (File.Exists(outputPath))
            {
                var outputFileInfo = new FileInfo(outputPath);
                await AppendDebugLogAsync($"[PdfExportService] ✅ PDF出力成功: {outputPath} (サイズ: {outputFileInfo.Length}バイト)");
            }
            else
            {
                await AppendDebugLogAsync($"[PdfExportService] ❌ PDF出力失敗: ファイルが作成されませんでした");
                return false;
            }
            
            _logger.LogInformation("[PdfExportService] PDF出力完了: {OutputPath}", outputPath);
            return true;
        }
        catch (Exception ex)
        {
            await AppendDebugLogAsync($"[PdfExportService] ❌ 致命的エラー: {ex.GetType().Name}: {ex.Message}");
            await AppendDebugLogAsync($"[PdfExportService] スタックトレース: {ex.StackTrace}");
            if (ex.InnerException != null)
            {
                await AppendDebugLogAsync($"[PdfExportService] 内部例外: {ex.InnerException.Message}");
            }
            
            _logger.LogError(ex, "[PdfExportService] PDF出力エラー: {Error}", ex.Message);
            return false;
        }
    }

        /// <summary>
        /// WYSIWYG PDF出力 - プレビュー状態を反映したPDF出力
        /// </summary>
        public async Task<bool> ExportCurrentStateAsync(
            IEnumerable<PdfExportPageData> pageData, 
            PdfQualitySettings qualitySettings,
            string outputPath,
            DocOrganizer.Application.Models.V3.PreviewState previewState)
        {
            try
            {
                var pageList = pageData.ToList();
                _logger.LogInformation("[PdfExportService] WYSIWYG PDF出力開始: {PageCount}ページ, 画質: {Quality}, 原寸大: {IsOriginal}", 
                    pageList.Count, qualitySettings.DisplayName, previewState.IsOriginalSize);

                // 🔧 詳細デバッグログ
                await AppendDebugLogAsync($"[PdfExportService] WYSIWYG出力パス: {outputPath}");
                await AppendDebugLogAsync($"[PdfExportService] プレビュー状態: IsOriginalSize={previewState.IsOriginalSize}, Zoom={previewState.CurrentZoomPercentage}%");
                
                for (int i = 0; i < pageList.Count; i++)
                {
                    var page = pageList[i];
                    await AppendDebugLogAsync($"[PdfExportService] Page{i}: ImagePath='{page.ImagePath}', Rotation={page.Rotation}");
                    
                    // ファイル存在確認
                    if (!File.Exists(page.ImagePath))
                    {
                        await AppendDebugLogAsync($"[PdfExportService] ❌ ファイル不存在: {page.ImagePath}");
                        throw new FileNotFoundException($"画像ファイルが見つかりません: {page.ImagePath}");
                    }
                }

                // 出力ディレクトリの作成
                var outputDir = Path.GetDirectoryName(outputPath);
                if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
                {
                    Directory.CreateDirectory(outputDir);
                }

                // PDFsharpを使用してPDF文書を作成
                using var document = new PdfSharpPdfDocument();
                
                // PDFメタデータ設定
                document.Info.Title = Path.GetFileNameWithoutExtension(outputPath);
                document.Info.Creator = "DocOrganizer V3.0 WYSIWYG";
                document.Info.Subject = "Generated by DocOrganizer";
                document.Info.CreationDate = DateTime.Now;

                for (int i = 0; i < pageList.Count; i++)
                {
                    var page = pageList[i];
                    await AppendDebugLogAsync($"[PdfExportService] ページ{i + 1}/{pageList.Count}の処理開始");
                    
                    OnProgressChanged(new PdfExportProgressEventArgs
                    {
                        CurrentPage = i + 1,
                        TotalPages = pageList.Count,
                        CurrentOperation = $"ページ {i + 1}/{pageList.Count} を処理中..."
                    });

                    try
                    {
                        await ProcessPageToPdfWithPreviewStateAsync(page, document, qualitySettings, previewState);
                        await AppendDebugLogAsync($"[PdfExportService] ページ{i + 1}処理完了");
                    }
                    catch (Exception pageEx)
                    {
                        await AppendDebugLogAsync($"[PdfExportService] ❌ ページ{i + 1}処理エラー: {pageEx.Message}");
                        throw new Exception($"ページ{i + 1}の処理でエラーが発生しました: {pageEx.Message}", pageEx);
                    }
                }

                // PDF保存
                OnProgressChanged(new PdfExportProgressEventArgs
                {
                    CurrentPage = pageList.Count,
                    TotalPages = pageList.Count,
                    CurrentOperation = "PDFファイルを保存中..."
                });

                document.Save(outputPath);
                
                // 保存結果確認
                if (File.Exists(outputPath))
                {
                    var outputFileInfo = new FileInfo(outputPath);
                    await AppendDebugLogAsync($"[PdfExportService] ✅ WYSIWYG PDF出力成功: {outputPath} (サイズ: {outputFileInfo.Length}バイト)");
                    _logger.LogInformation("[PdfExportService] WYSIWYG PDF出力完了: {OutputPath}", outputPath);
                    return true;
                }
                
                return false;
            }
            catch (Exception ex)
            {
                await AppendDebugLogAsync($"[PdfExportService] ❌ 致命的エラー: {ex.Message}");
                _logger.LogError(ex, "[PdfExportService] WYSIWYG PDF出力エラー: {Error}", ex.Message);
                return false;
            }
        }

        /// <summary>
        /// プレビュー状態を反映したページ処理
        /// </summary>
        private async Task ProcessPageToPdfWithPreviewStateAsync(
            PdfExportPageData pageData, 
            PdfSharpPdfDocument document, 
            PdfQualitySettings qualitySettings,
            DocOrganizer.Application.Models.V3.PreviewState previewState)
        {
            try
            {
                await AppendDebugLogAsync($"[ProcessPageWithPreviewState] 開始: {pageData.ImagePath}");
                
                // 画像データを処理
                var imageBytes = await ProcessPageImageAsync(pageData, qualitySettings);
                await AppendDebugLogAsync($"[ProcessPageWithPreviewState] 画像処理完了: {imageBytes.Length}バイト");

                // 画像のサイズを取得
                using var ms = new MemoryStream(imageBytes);
                using var img = await SixLabors.ImageSharp.Image.LoadAsync(ms);
                var imageWidth = img.Width;
                var imageHeight = img.Height;

                // PDFページを作成（プレビュー状態に基づく）
                var page = document.AddPage();
                
                if (previewState.IsOriginalSize)
                {
                    // 原寸大：画像のサイズをそのまま使用
                    // ピクセルからポイントへ変換（1インチ = 72ポイント = 96ピクセル）
                    page.Width = XUnit.FromPoint(imageWidth * 72.0 / 96.0);
                    page.Height = XUnit.FromPoint(imageHeight * 72.0 / 96.0);
                    await AppendDebugLogAsync($"[ProcessPageWithPreviewState] 原寸大モード: {page.Width}pt x {page.Height}pt");
                }
                else
                {
                    // A4フィット
                    page.Size = PdfSharp.PageSize.A4;
                    page.Orientation = PdfSharp.PageOrientation.Portrait;
                    await AppendDebugLogAsync($"[ProcessPageWithPreviewState] A4フィットモード: {page.Width}pt x {page.Height}pt");
                }

                // XGraphicsを作成
                using var gfx = XGraphics.FromPdfPage(page);

                // XImageを作成（一時ファイル経由）
                var tempFilePath = Path.GetTempFileName() + ".jpg";
                try
                {
                    await File.WriteAllBytesAsync(tempFilePath, imageBytes);
                    using var image = XImage.FromFile(tempFilePath);

                    if (previewState.IsOriginalSize)
                    {
                        // 原寸大：そのまま描画（余白なし）
                        gfx.DrawImage(image, 0, 0, page.Width, page.Height);
                        await AppendDebugLogAsync("[ProcessPageWithPreviewState] 原寸大描画完了");
                    }
                    else
                    {
                        // A4フィット：プレビューと同じ計算で中央配置
                        var pageSize = new XSize(page.Width, page.Height);
                        var imageSize = new SixLabors.ImageSharp.Size(image.PixelWidth, image.PixelHeight);
                        var drawRect = CalculateDrawingRectangle(imageSize, pageSize);
                        
                        // 白背景（プレビューと同じ）
                        gfx.DrawRectangle(XBrushes.White, 0, 0, page.Width, page.Height);
                        
                        // 画像を描画
                        gfx.DrawImage(image, drawRect);
                        await AppendDebugLogAsync($"[ProcessPageWithPreviewState] A4フィット描画完了: {drawRect.Width}x{drawRect.Height}");
                    }
                }
                finally
                {
                    // 一時ファイルの削除
                    if (File.Exists(tempFilePath))
                    {
                        File.Delete(tempFilePath);
                    }
                }

                await AppendDebugLogAsync($"[ProcessPageWithPreviewState] ページ処理完了: {pageData.ImagePath}");
            }
            catch (Exception ex)
            {
                await AppendDebugLogAsync($"[ProcessPageWithPreviewState] ❌ エラー: {ex.Message}");
                throw;
            }
        }

    public async Task<byte[]> ProcessPageImageAsync(PdfExportPageData pageData, PdfQualitySettings qualitySettings)
    {
        try
        {
            _logger.LogDebug("[PdfExportService] 画像処理開始: {ImagePath}, 回転: {Rotation}度",
                pageData.ImagePath, pageData.Rotation);

            var imagePath = pageData.ImagePath;

            // ✅ HEIC判定と事前変換
            if (IsHeicFile(imagePath))
            {
                _logger.LogDebug("[PdfExportService] HEIC形式を検出、JPEG変換を実行: {OriginalPath}", imagePath);
                await AppendDebugLogAsync($"[ProcessPageImageAsync] HEIC形式検出: {imagePath}");

                // HeicConversionServiceを使用してJPEG変換
                imagePath = await _heicConversionService.ConvertHeicToTempJpegAsync(imagePath);

                _logger.LogDebug("[PdfExportService] HEIC→JPEG変換完了: {ConvertedPath}", imagePath);
                await AppendDebugLogAsync($"[ProcessPageImageAsync] HEIC→JPEG変換完了: {imagePath}");
            }

            // 🎯 V3.0.111: 余白削除を適用（ユーザー要求：余白は絶対に必要なし）
            ImageMagick.MagickImage magickImage;
            if (_autoCropService != null)
            {
                var trimmedBytes = await _autoCropService.TrimWhitespaceAsync(imagePath);
                magickImage = new ImageMagick.MagickImage(trimmedBytes);
            }
            else
            {
                magickImage = new ImageMagick.MagickImage(imagePath);
            }

            using (magickImage)
            {
                // EXIF自動回転（Magick.NET）
                magickImage.AutoOrient();
                await AppendDebugLogAsync($"[ProcessPageImageAsync] AutoOrient()適用完了");

                // 回転適用
                if (pageData.Rotation > 0)
                {
                    magickImage.Rotate(pageData.Rotation);
                    _logger.LogDebug("[PdfExportService] 画像回転適用: {Rotation}度", pageData.Rotation);
                    await AppendDebugLogAsync($"[ProcessPageImageAsync] 追加回転適用: {pageData.Rotation}度");
                }

                // 画質設定に基づくリサイズ
                var currentWidth = (int)magickImage.Width;
                var currentHeight = (int)magickImage.Height;
                var currentSize = new SixLabors.ImageSharp.Size(currentWidth, currentHeight);
                var targetSize = CalculateTargetSize(currentSize, qualitySettings);

                if (targetSize != currentSize)
                {
                    magickImage.Resize((uint)targetSize.Width, (uint)targetSize.Height);
                    _logger.LogDebug("[PdfExportService] 画像リサイズ: {OriginalSize} → {TargetSize}",
                        currentSize, targetSize);
                    await AppendDebugLogAsync($"[ProcessPageImageAsync] リサイズ完了: {currentSize} → {targetSize}");
                }

                // JPEG形式でエンコード
                using var ms = new MemoryStream();
                magickImage.Quality = (uint)qualitySettings.CompressionLevel;
                magickImage.Format = ImageMagick.MagickFormat.Jpeg;
                magickImage.Write(ms);

                await AppendDebugLogAsync($"[ProcessPageImageAsync] JPEG保存完了: {ms.Length}バイト, 品質: {qualitySettings.CompressionLevel}");
                return ms.ToArray();
            }
        }
        catch (Exception ex)
        {
            await AppendDebugLogAsync($"[ProcessPageImageAsync] ❌ 画像処理エラー: {ex.Message}");
            _logger.LogError(ex, "[PdfExportService] 画像処理エラー: {ImagePath}, {Error}",
                pageData.ImagePath, ex.Message);
            throw;
        }
    }

    private async Task ProcessPageToPdfAsync(PdfExportPageData pageData, PdfSharpPdfDocument document, PdfQualitySettings qualitySettings)
    {
        try
        {
            await AppendDebugLogAsync($"[ProcessPageToPdfAsync] 開始: {pageData.ImagePath}");
            
            // 画像データを処理
            var imageBytes = await ProcessPageImageAsync(pageData, qualitySettings);
            await AppendDebugLogAsync($"[ProcessPageToPdfAsync] 画像処理完了: {imageBytes.Length}バイト");

            // PDFページを作成 - 画像サイズに完全一致させる
            var page = document.AddPage();

            // 画像の実際のサイズを取得してページサイズを決定
            using var tempImage = XImage.FromStream(new MemoryStream(imageBytes));
            var imageWidthInPoints = tempImage.PixelWidth * 72.0 / 96.0; // 96 DPIを72ポイントに変換
            var imageHeightInPoints = tempImage.PixelHeight * 72.0 / 96.0;

            // ページサイズを画像サイズに完全一致させる（余白完全排除）
            page.Width = XUnit.FromPoint(imageWidthInPoints);
            page.Height = XUnit.FromPoint(imageHeightInPoints);
            page.Orientation = PdfSharp.PageOrientation.Portrait;
            
            await AppendDebugLogAsync($"[ProcessPageToPdfAsync] PDFページ作成完了: {page.Width}pt x {page.Height}pt");

            // XGraphicsを作成
            using var gfx = XGraphics.FromPdfPage(page);
            await AppendDebugLogAsync("[ProcessPageToPdfAsync] XGraphics作成完了");

            // XImageを作成（一時ファイル経由）
            var tempFilePath = Path.GetTempFileName() + ".jpg";
            try
            {
                await File.WriteAllBytesAsync(tempFilePath, imageBytes);
                await AppendDebugLogAsync($"[ProcessPageToPdfAsync] 一時ファイル作成: {tempFilePath}");
                using var image = XImage.FromFile(tempFilePath);
            await AppendDebugLogAsync($"[ProcessPageToPdfAsync] XImage作成完了: {image.PixelWidth}x{image.PixelHeight}");

            // ページ全体に画像を描画（余白なし）
            // ページサイズは既に画像サイズに一致しているため、0,0から全体に描画
            var drawRect = new XRect(0, 0, page.Width.Point, page.Height.Point);

            await AppendDebugLogAsync($"[ProcessPageToPdfAsync] 描画矩形: {drawRect.X}, {drawRect.Y}, {drawRect.Width}, {drawRect.Height}");

            // 画像を描画
            await AppendDebugLogAsync("[ProcessPageToPdfAsync] 画像描画開始");
            gfx.DrawImage(image, drawRect);
            await AppendDebugLogAsync("[ProcessPageToPdfAsync] 画像描画完了");

                await AppendDebugLogAsync($"[ProcessPageToPdfAsync] ページ処理完了: {pageData.ImagePath}");
                _logger.LogDebug("[PdfExportService] PDFページ追加完了: {ImagePath}", pageData.ImagePath);
            }
            finally
            {
                // 一時ファイルの削除
                if (File.Exists(tempFilePath))
                {
                    File.Delete(tempFilePath);
                    await AppendDebugLogAsync($"[ProcessPageToPdfAsync] 一時ファイル削除: {tempFilePath}");
                }
            }
        }
        catch (Exception ex)
        {
            await AppendDebugLogAsync($"[ProcessPageToPdfAsync] ❌ エラー: {ex.GetType().Name}: {ex.Message}");
            await AppendDebugLogAsync($"[ProcessPageToPdfAsync] スタックトレース: {ex.StackTrace}");
            
            _logger.LogError(ex, "[PdfExportService] PDFページ処理エラー: {ImagePath}, {Error}", 
                pageData.ImagePath, ex.Message);
            throw;
        }
    }

    private SixLabors.ImageSharp.Size CalculateTargetSize(SixLabors.ImageSharp.Size currentSize, PdfQualitySettings qualitySettings)
    {
        var maxWidth = qualitySettings.MaxWidth;
        var maxHeight = qualitySettings.MaxHeight;

        // 最高画質の場合（MaxWidth=0, MaxHeight=0）は元画像サイズそのまま
        if (maxWidth == 0 && maxHeight == 0)
        {
            return currentSize;
        }

        if (currentSize.Width <= maxWidth && currentSize.Height <= maxHeight)
        {
            return currentSize;
        }

        var widthRatio = (double)maxWidth / currentSize.Width;
        var heightRatio = (double)maxHeight / currentSize.Height;
        var ratio = Math.Min(widthRatio, heightRatio);

        return new SixLabors.ImageSharp.Size(
            (int)(currentSize.Width * ratio),
            (int)(currentSize.Height * ratio)
        );
    }

    private XRect CalculateDrawingRectangle(SixLabors.ImageSharp.Size imageSize, XSize pageSize)
    {
        // 【重要】余白は絶対に必要なし - ページ全体を画像で埋める
        // ユーザー要求: プレビューとPDF出力を完全一致させる（WYSIWYG原則）
        // 画像がページ全体を覆うようにし、必要に応じて画像の一部をクロップ

        var pageAspect = pageSize.Width / pageSize.Height;
        var imageAspect = (double)imageSize.Width / imageSize.Height;

        double width, height;
        double x = 0, y = 0;

        if (imageAspect > pageAspect)
        {
            // 画像が横長：高さをページ高さに合わせ、横幅は中央部分を使用
            height = pageSize.Height;
            width = height * imageAspect;
            x = -(width - pageSize.Width) / 2; // 左右の余剰部分を均等にクロップ
        }
        else
        {
            // 画像が縦長：幅をページ幅に合わせ、高さは中央部分を使用
            width = pageSize.Width;
            height = width / imageAspect;
            y = -(height - pageSize.Height) / 2; // 上下の余剰部分を均等にクロップ
        }

        // ページ全体を埋める（余白なし）
        return new XRect(x, y, width, height);
    }

    private void OnProgressChanged(PdfExportProgressEventArgs e)
    {
        ProgressChanged?.Invoke(this, e);
    }

    /// <summary>
    /// 🚨 緊急デバッグ: ファイルに詳細ログを出力（第16条準拠）
    /// </summary>
    private async Task AppendDebugLogAsync(string message)
    {
        try
        {
            await DocOrganizer.Core.Logging.DebugLogger.LogAsync(message, "PDF_EXPORT_DEBUG");
        }
        catch
        {
            // ログ出力エラーは無視
        }
    }

    /// <summary>
    /// HEIC形式のファイルかどうかを判定
    /// </summary>
    private static bool IsHeicFile(string filePath)
    {
        var extension = Path.GetExtension(filePath).ToLowerInvariant();
        return extension == ".heic" || extension == ".heif";
    }
}